server:
  port: 8080

# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datamaster?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari 连接池配置
    # 最小空闲连接数量
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# MyBatis
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# log
logging:
#  level:
#      com.pedro.infrastructure.dao: debug
  file:
    name: G:/code/DataMaster/log/DataMaster.log

pedro-auth:
  auth-level:
    # default只支持noAuth和needAuth
    default: needAuth
    rule-list: rule1,rule2,rule3,rule4,rule5
    rule1:
      path: /jumpToLoginPage
      level: noAuth
    rule2:
      path: /login
      level: noAuth
    rule3:
      path: /jumpToRegistryPage
      level: noAuth
    rule4:
      path: /registry
      level: noAuth
    rule5:
      path: /roleDenied
      level: noAuth
  no-auth-path: /jumpToLoginPage
  no-role-path: /roleDenied